on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: build image
        uses: docker/bake-action@v3
        with:
          push: false
          load: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          workdir: .devcontainer

      - name: build site
        run: docker compose run dev haunt build

      - name: upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: site
  
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v2
